/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pf_ffmpegdemo_MainActivity */

#ifndef _Included_com_pf_ffmpegdemo_MainActivity
#define _Included_com_pf_ffmpegdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pf_ffmpegdemo_MainActivity
 * Method:    openFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pf_ffmpegdemo_MainActivity_openFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
